### ISSUE TITLE
Driver update function signature

### ISSUE THREAD

**Issue by nitriques** [Solutions-Nitriques/anti_brute_force#31]
It does not contain a second parameter anymore. (2.6)

Maybe use a default value ?

New signature: 

```php
public function update($previousVersion = false)
```

**Comment by michael-e** [comment]
I don' really understand what you mean. The function already has this signature, since https://github.com/Solutions-Nitriques/anti_brute_force/commit/3ecc11168fc6012c29375a1bedda14a48226b66b

**Comment by nitriques** [comment]
Well, that's even better :) Thanks!
