### ISSUE TITLE
Compatibility with Symphony 2.6

### ISSUE THREAD

**Issue by michael-e** [Solutions-Nitriques/anti_brute_force#32]
Now that Symphony 2.6 is out for a while, we should have a version of the extension that is "officially" compatible.

**Comment by nitriques** [comment]
Yup. I did test it with 2.6, but not thoroughly. Have you ?

**Comment by michael-e** [comment]
Same here, I just left it running… :-)

**Comment by nitriques** [comment]
Ok well, I'll make some basic tests and release a new version when I am confident that it not broken in 2.6. Thanks for the reminder Michael!

**Comment by michael-e** [comment]
You're welcome. Thanks for caring!

**Comment by michael-e** [comment]
Bump. :-)

**Comment by nitriques** [comment]
I never had the chance to properly test it, and it seems like the grey list is not working anymore... Have you experienced this ?

**Comment by michael-e** [comment]
It seems to work for me. Is it supposed to do anything more than count the failed attempts for IP addresses?

**Comment by nitriques** [comment]
Yes. It is supposed to record an entry in the greylist, and count the number of BANS (not the number of failed attempt). It is also suppose to move the record into the black list when the limit numbers of bans are reach.

**Comment by michael-e** [comment]
Yep, numer of bans, sure. That is working fine.

How many bans do I need to move an entry to the blacklist?

**Comment by nitriques** [comment]
Default value is 5. You can change it to whatever in the preferences page.

**Comment by michael-e** [comment]
It works like a charm for me. In my eyes this extension is much more "2.6 compatible" than many others!

**Comment by nitriques** [comment]
LOL! Which exact version of Sym did you test ?

**Comment by michael-e** [comment]
2.6.2

**Comment by michael-e** [comment]
(Or even more, 2.6.x, which is the 2.6 branch…)

**Comment by nitriques** [comment]
Ok since you confirm that the greylist works, I'll release a new version right now. ;)

**Comment by michael-e** [comment]
Trust me. I would have broken it if possible. :-))

**Comment by nitriques** [comment]
I have 100% trust in you Michael ;)

**Comment by nitriques** [comment]
https://github.com/Solutions-Nitriques/anti_brute_force/releases/tag/v1.4.8

**Comment by nitriques** [comment]
Thanks again!

**Comment by michael-e** [comment]
Thank you!
