### ISSUE TITLE
Rename mistyped function

### ISSUE THREAD

**Issue by michael-e** [Solutions-Nitriques/anti_brute_force#34]
The callback function name `initaliseAdminPageHead` is a typo. The function is public, so correcting the typo would require releasing a new major version (2.0). Nevertheless I suggest to do it (because I don't expect that any other extension ever called this public function).

If you like, I can send a PR for this after #33 has been pulled.

**Comment by nitriques** [comment]
Yes please! #31 should be addressed too (I can to it, no worries)

**Comment by michael-e** [comment]
I will send a PR and make it version 2.0, as suggested above.

**Comment by nitriques** [comment]
Awesome!
