### ISSUE TITLE
Inline event handlers should be removed

### ISSUE THREAD

**Issue by michael-e** [Solutions-Nitriques/anti_brute_force#38]
In [this line](https://github.com/Solutions-Nitriques/anti_brute_force/blob/2.0.2/lib/class.ViewFactory.php#L136) inline event handlers are added.

However, inline event handlers should be avoided.

(I wouldn't care removing these buttons altogether, because you can as well use the menu to navigate between lists. I always saw the buttons as a "superfluous second way to do something".)

**Comment by nitriques** [comment]
LOL. It saves times ;)

**Comment by nitriques** [comment]
Fixed in 1ce59c0
